# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine AS build
WORKDIR /app
RUN apk add --no-cache python3 make g++
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src
RUN npm ci
RUN npm run build

FROM node:lts-alpine
WORKDIR /app
COPY --from=build /app/build ./build
COPY package.json package-lock.json ./
RUN npm ci --omit=dev --ignore-scripts

CMD ["node", "build/index.js"]
